### ISSUE TITLE
A new Feature

### ISSUE THREAD

**Issue by MOlausson** [SolidifyDemo/recator-modern-dev-gh#21]
# Introduction

# Solution

Some basic Git commands are:
```
git status
git add
git commit
```
```ruby
require 'redcarpet'
markdown = Redcarpet.new("Hello World!")
puts markdown.to_html
```

```[tasklist]
### Tasks
- [ ] https://github.com/SolidifyDemo/recator-modern-dev-gh/issues/22
- [ ] https://github.com/SolidifyDemo/recator-modern-dev-gh/issues/23
- [ ] https://github.com/SolidifyDemo/recator-modern-dev-gh/issues/24
```

**Comment by MOlausson** [comment]
@MOlausson look at this.

**Comment by MOlausson** [comment]
```mermaid

---
title: Animal example
---
classDiagram
    note "From Duck till Zebra"
    Animal <|-- Duck
    note for Duck "can fly\ncan swim\ncan dive\ncan help in debugging"
    Animal <|-- Fish
    Animal <|-- Zebra
    Animal : +int age
    Animal : +String gender
    Animal: +isMammal()
    Animal: +mate()
    class Duck{
        +String beakColor
        +swim()
        +quack()
    }
    class Fish{
        -int sizeInFeet
        -canEat()
    }
    class Zebra{
        +bool is_wild
        +run()
    }


```

**Comment by MOlausson** [comment]
#22 may be a duplicate?
